name: news_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.12


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  bloc_test: ^9.1.4
  mockito: ^5.4.2


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

